version: '3'
services:
  mongo:
    image: mongo:4.0
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
  kv:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
  app:
    image: message-app:0.16 # New version taking into account REDIS_HOST
    ports:
      - "8000:80"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/messageApp
      - REDIS_HOST=kv
volumes:
  mongo-data:
  redis-data:
